-- Add missing user roles to UserRole enum

ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'HOD_PREPRESS';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'DESIGNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'QA_PREPRESS';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'CTP_OPERATOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'INVENTORY_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'PROCUREMENT_MANAGER';

-- Show all roles
SELECT enumlabel as role FROM pg_enum WHERE enumtypid = '"UserRole"'::regtype ORDER BY enumlabel;

